# Generated by Django 2.1.3 on 2018-11-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eggu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='sandwich',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
